spring:
  application:
    name: forest-project

  datasource:
    url: jdbc:mysql://localhost:3306/forest-economy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2915227089

mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致